In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a


In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix


In [ ]:
a[0]


In [ ]:
matrix[1, 1]


In [ ]:
matrix[1:, :2]


In [ ]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)


In [ ]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)


In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1


In [ ]:
np.random.randn(10)


In [ ]:
np.random.randn(3, 4)


In [ ]:
mu = 100
sigma = 30

sigma * np.random.randn(20) + mu


In [ ]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))

In [ ]:
print('np.ones(3)     == {}'.format(np.ones(3)))

In [ ]:
print('np.full(3, 17) == {}'.format(np.full(3, 17)))

In [ ]:
np.zeros((2, 3))


In [ ]:
np.arange(4)


In [ ]:
np.arange(1, 4)


In [ ]:
np.arange(3, 5, 0.5)


In [ ]:
a = np.array([1, 2, 3, 4, 5])


In [ ]:
a.min()


In [ ]:
a.max()


In [ ]:
a.mean()


In [ ]:
a.sum()


In [ ]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


How many negative numbers are there?

In [ ]:
number_of_neg = len(a[a < 0])
number_of_neg

In [ ]:
How many positive numbers are there?

In [ ]:
number_of_pos = a[a > 0]
How many even positive numbers are there?


How many even positive numbers are there?

In [ ]:
number_of_even_pos = a[(a % 2 == 0) & (a > 0)]
number_of_even_pos

If you were to add 3 to each data point, how many positive numbers would there be?

In [ ]:
add_three = a + 3

add_three

In [ ]:
number_of_pos_int = len(add_three[add_three > 0])
number_of_pos_int

If you squared each number, what would the new mean and standard deviation be?

In [ ]:
# old mean
a.mean()


In [ ]:
#old STD
a.std()


In [ ]:
 new_a = a**2
new_a

In [ ]:
#new mean

new_a.mean()

In [ ]:
#old mean
new_a.std()

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [ ]:
old_mean = a.mean()
old_mean

In [ ]:
Question_6 = a - old_mean

In [ ]:
Question_6.mean()

Calculate the z-score for each data point. Recall that the z-score is given by:

In [ ]:
a

In [ ]:
new_z = a - a.mean() / a.std()
new_z

In [ ]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#Use python's built in functionality/operators to determine the following:
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [97]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [98]:
sum_of_a = a.sum()
sum_of_a

55

 Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [ ]:
min_of_a = a.min()

In [ ]:
min_of_a

 Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [ ]:
max_of_a = a.max()

In [ ]:
max_of_a

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [99]:
mean_of_a = a.mean()

In [100]:
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [104]:
product_of_a = a.prod()

In [105]:
product_of_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [ ]:
squares_of_a = a**2 

In [ ]:
squares_of_a

#Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [ ]:
odds_in_a = a[a % 2 == 1]

In [ ]:
odds_in_a

#Exercise 8 - Make a variable named evens_in_a. It should hold only the evens

In [ ]:
evens_in_a = a[a % 2 == 0]

In [ ]:
evens_in_a

##What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
##Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [18]:
import numpy as np

In [19]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])


In [20]:
b


array([[3, 4, 5],
       [6, 7, 8]])

In [4]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)


In [5]:
sum_of_b

33

In [6]:
b.sum()

33

In [ ]:
# Exercise 2 - refactor the following to use numpy. 

In [8]:
n_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [9]:
n_of_b

3

In [10]:
b.min()

3

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [13]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [11]:
b.max()

8

In [ ]:
# Exercise 4 - refactor the following using numpy to find the mean of b

In [15]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [16]:
b.mean()

5.5

In [ ]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [18]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [27]:
np.prod(b)


20160

In [ ]:
# Exercise 6 - refactor the following to use numpy to find the list of squares

In [23]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [25]:
b*b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
# Exercise 7 - refactor using numpy to determine the odds_in_b

In [29]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [35]:
odds_in = b[b % 2 != 0]
odds_in

array([3, 5, 7])

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [37]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
evens_in_b

[4, 6, 8]

In [38]:
b[b % 2 == 0]

array([4, 6, 8])

In [ ]:
# Exercise 9 - print out the shape of the array b.

In [14]:
import matplotlib.pyplot as plt

In [23]:
print(b.shape)

(2, 3)


In [ ]:
# Exercise 10 - transpose the array b.

In [24]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [26]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [27]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [6]:
## Setup 3
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [5]:
import numpy as np

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
#Exercise 1 - Find the min, max, sum, and product of c.


In [7]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
c.max()

9

In [10]:
c.min()

1

In [11]:
c.sum()

45

In [ ]:
# Exercise 2 - Determine the standard deviation of c.

In [12]:
c.std()

2.581988897471611

In [ ]:
# Exercise 3 - Determine the variance of c.

In [13]:
c.var()

6.666666666666667

In [ ]:
# Exercise 4 - Print out the shape of the array c

In [29]:
print(b.shape)

(2, 3)


In [ ]:
# Exercise 5 - Transpose c and print out transposed result.

In [30]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 

In [32]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [41]:
(c * c.transpose()).sum()

261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [42]:
(c * c.transpose()).prod()

131681894400

In [71]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [72]:
d


array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

In [66]:
import math

In [106]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d

In [87]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [88]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [80]:
d[d < 0]

array([-90, -30, -45, -45])

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [81]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d

In [89]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [90]:
len(np.unique(d))

11

In [ ]:
# Exercise 8 - Print out the shape of d.

In [91]:
print(d.shape)

(3, 6)


In [ ]:

# Exercise 9 - Transpose and then print out the shape of d.

In [95]:
d.transpose()

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [ ]:

# Exercise 10 - Reshape d into an array of 9 x 2

In [96]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])